# Generated by Django 5.1.2 on 2024-11-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_alter_vehiculo_precio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': (('visualizar_catalogo', 'Ver Catalogo Vehiculos'), ('add_vehiculomodel', 'Agregar Vehiculo'))},
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='categoria',
            field=models.CharField(choices=[('PARTICULAR', 'PARTICULAR'), ('TRANSPORTE', 'TRANSPORTE'), ('CARGA', 'CARGA')], default='Particular', max_length=20),
        ),
    ]
