# Generated by Django 5.1.2 on 2024-11-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0003_alter_vehiculo_options_alter_vehiculo_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(choices=[('CHEVROLET', 'CHEVROLET'), ('FIAT', 'FIAT'), ('FORD ', 'FORD'), ('TOYOTA', 'TOYOTA')], default='Ford', max_length=20),
        ),
    ]
