# Generated by Django 5.1.2 on 2024-11-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0005_alter_vehiculo_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(choices=[('CHEVROLET', 'CHEVROLET'), ('FIAT', 'FIAT'), ('FORD', 'FORD'), ('TOYOTA', 'TOYOTA')], default='Ford', max_length=20),
        ),
    ]
